version: "3.8"

services:
  fastapi:
    container_name: fastapi_app
    build: .
    ports:
      - "8000:8000"
    restart: always
    environment:
      - ENVIRONMENT=production
      - LOG_LEVEL=info
