name: Deploy FastAPI to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy to EC2
        env:
          HOST: ec2-13-215-182-72.ap-southeast-1.compute.amazonaws.com
          KEY: ${{ secrets.EC2_KEY }}
          BDFARE_BASE_URL: ${{ secrets.BDFARE_BASE_URL }}
          BDFARE_API_KEY: ${{ secrets.BDFARE_API_KEY }}
          FLYHUB_USERNAME: ${{ secrets.FLYHUB_USERNAME }}
          FLYHUB_API_KEY: ${{ secrets.FLYHUB_API_KEY }}
          FLYHUB_PRODUCTION_URL: ${{ secrets.FLYHUB_PRODUCTION_URL }}
          USER: ubuntu
        run: |
          echo "$KEY" > api.pem
          chmod 400 api.pem

          ssh -o StrictHostKeyChecking=no -i api.pem $USER@$HOST << 'EOF'
          cd /home/ubuntu/travelapi
          git pull origin main
          source venv/bin/activate
          pip install -r requirements.txt

          # Create .env file on EC2
          echo "BDFARE_BASE_URL=$BDFARE_BASE_URL" > .env
          echo "BDFARE_API_KEY=$BDFARE_API_KEY" >> .env
          echo "FLYHUB_USERNAME=$FLYHUB_USERNAME" >> .env
          echo "FLYHUB_API_KEY=$FLYHUB_API_KEY" >> .env
          echo "FLYHUB_PRODUCTION_URL=$FLYHUB_PRODUCTION_URL" >> .env

          nohup uvicorn main:app --host 0.0.0.0 --port 8000 --reload &
          EOF
