name: CI/CD for Travel API

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # CI Job: Build, Test, Lint
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Specify your Python version

      - name: Set up virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Linter (Flake8)
        run: |
          pip install flake8
          flake8 .  # Lint all Python files in the repository

      - name: Run Tests
        run: |
          pip install pytest
          pytest  # Run all tests in your repository

  # CD Job: Deployment (This example assumes a simple deploy to a remote server using SSH)
  deploy:
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Production
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}  # You should add your SSH key in GitHub secrets
        run: |
          echo "Deploying to production..."
          ssh -o StrictHostKeyChecking=no -i $DEPLOY_KEY user@your-server-ip 'cd /path/to/your/app && git pull && systemctl restart travel-api'

